on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wranders/markdown-to-pages-action@v1
      with:
        title: "Lauftreff Wettringen"
        token: ${{ secrets.GITHUB_TOKEN }}
        files: 
          geldeinsammeln-heinz.md
          geldeinsammeln-kaisers.md
    - run: cp -r ./images ./dist/images/
    - uses: actions/upload-pages-artifact@v3
      with:
        path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/deploy-pages@v4
      id: deployment
